openapi: 3.0.0
info:
  contact:
    email: xiachengjia@speakin.mobi
  description: api document
  license:
    name: Mit
    url: https://opensource.org/licenses/MIT
  title: 声纹云api
  version: /cloudapi/v1beta
servers:
- description: dev
  url: https://vpc.speakin.mobi
tags:
- name: storage
- name: voiceprint
paths:
  /cloudapi/v1beta/voiceprint/verify1ton:
    post:
      description: 声纹验证
      operationId: verify1ton
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Voiceprint1tonVerifyRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprint1tonVerifyResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/agc:
    post:
      description: 增益
      operationId: agc
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintAgcRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintAgcResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/clips:
    post:
      description: 有效音
      operationId: clips
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintClipsRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintClipsResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/ctcdasr:
    post:
      description: 数字asr
      operationId: ctcdasr
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintCtcdasrRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintCtcdasrResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/delete:
    post:
      description: 声纹查询
      operationId: delete
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintDeleteRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintDeleteResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/denoise:
    post:
      description: 降噪算法
      operationId: denoise
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintDenoiseRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintDenoiseResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/mos:
    post:
      description: 计算mos值
      operationId: mos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintMosRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintMosResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/query:
    post:
      description: 声纹查询
      operationId: query
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintQueryRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintQueryResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/register:
    post:
      description: 声纹注册
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintRegisterRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintRegisterResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/split:
    post:
      description: 人声分离
      operationId: split
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintSplitRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintSplitResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/threshold:
    post:
      description: 查询阈值
      operationId: threshold
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintThresholdRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintThresholdResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/dynamicthreshold:
    post:
      description: 查询动态阈值
      operationId: dynamicthreshold
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintDynamicThresholdRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintDynamicThresholdResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/vadcheck:
    post:
      description: VAD检测
      operationId: vadcheck
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintVadcheckRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintVadcheckResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/verify:
    post:
      description: 声纹验证
      operationId: verify
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintVerifyRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintVerifyResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/verify_multi:
    post:
      description: 声纹验证1对多
      operationId: verify_multi
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintVerifyMultiRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintVerifyMultiResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/verifytopn:
    post:
      description: 声纹验证
      operationId: verifytopn
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprinttopnVerifyRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprinttopnVerifyResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/normalize:
    post:
      description: 分数归一化
      operationId: normalize
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintNormalizeRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintNormalizeResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/emotion:
    post:
      description: 情绪识别
      operationId: emotion
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintEmotionRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintEmotionResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/gender:
    post:
      description: 性别识别
      operationId: gender
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintGenderRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintGenderResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/voiceprint/tts:
    post:
      description: 录音攻击
      operationId: tts
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceprintTTSRequest'
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RespVoiceprintTTSResponse'
          description: 响应参数
      tags:
      - voiceprint
  /cloudapi/v1beta/storage/upload:
    post:
      description: 上传文件
      operationId: upload
      parameters:
      - description: 桶id
        explode: true
        in: query
        name: bucket
        required: true
        schema:
          type: string
        style: form
      - description: 文件类型
        explode: true
        in: query
        name: type
        required: true
        schema:
          example: wav
          type: string
        style: form
      - description: 时长
        explode: true
        in: query
        name: durationMS
        required: false
        schema:
          example: 0
          format: int64
          type: integer
        style: form
      - description: 时间戳
        explode: true
        in: query
        name: timestamp
        required: true
        schema:
          example: 123
          format: int64
          type: integer
        style: form
      requestBody:
        content:
          application/octet-stream:
            schema:
              format: binary
              type: string
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/body'
        description: 上传文件
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallUploadResponse'
          description: 响应参数
      tags:
      - storage
  /cloudapi/v1beta/storage/download:
    get:
      description: 下载文件
      operationId: download
      parameters:
      - description: 桶id
        explode: true
        in: query
        name: bucket
        required: true
        schema:
          type: string
        style: form
      - description: 文件key
        explode: true
        in: query
        name: key
        required: true
        schema:
          example: "123"
          type: string
        style: form
      responses:
        200:
          content:
            application/octet-stream:
              schema:
                format: binary
                type: string
          description: 二进制文件
      tags:
      - storage
components:
  schemas:
    CallUploadResponse:
      example:
        errorDesc: errorDesc
        data:
          key: "123"
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/UploadResponse'
      type: object
      xml:
        name: CallUploadResponse
    RespVoiceprint1tonVerifyResponse:
      example:
        errorDesc: errorDesc
        data:
          score: 0.5
          unionID: "123"
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/Voiceprint1tonVerifyResponse'
      type: object
      xml:
        name: RespVoiceprint1tonVerifyResponse
    RespVoiceprintAgcResponse:
      example:
        errorDesc: errorDesc
        data:
          key: xx_xxxxx-xxxxx
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprintAgcResponse'
      type: object
      xml:
        name: RespVoiceprintAgcResponse
    RespVoiceprintClipsResponse:
      example:
        errorDesc: errorDesc
        data:
          ringingSlice:
          - startMS: 0
            endMS: 0
          - startMS: 0
            endMS: 0
          humanSlice:
          - startMS: 0
            endMS: 3000
          - startMS: 5000
            endMS: 8000
          musicSlice:
          - startMS: 0
            endMS: 0
          - startMS: 0
            endMS: 0
          silentSlice:
          - startMS: 0
            endMS: 0
          - startMS: 0
            endMS: 0
          broadcastSlice:
          - startMS: 0
            endMS: 0
          - startMS: 0
            endMS: 0
          busySignalSlice:
          - startMS: 0
            endMS: 0
          - startMS: 0
            endMS: 0
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprintClipsResponse'
      type: object
      xml:
        name: RespVoiceprintClipsResponse
    RespVoiceprintCtcdasrResponse:
      example:
        errorDesc: errorDesc
        data:
          asrString: "123456"
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprintCtcdasrResponse'
      type: object
      xml:
        name: RespVoiceprintCtcdasrResponse
    RespVoiceprintDeleteResponse:
      example:
        errorDesc: errorDesc
        data: ""
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          xml:
            name: VoiceprintDeleteResponse
      type: object
      xml:
        name: RespVoiceprintDeleteResponse
    RespVoiceprintDenoiseResponse:
      example:
        errorDesc: errorDesc
        data:
          string: "22"
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprintDenoiseResponse'
      type: object
      xml:
        name: RespVoiceprintDenoiseResponse
    RespVoiceprintDynamicThresholdResponse:
      example:
        errorDesc: errorDesc
        data:
          threshold: 0.38
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprintDynamicThresholdResponse'
      type: object
      xml:
        name: RespVoiceprintDynamicThresholdResponse
    RespVoiceprintEmotionResponse:
      example:
        errorDesc: errorDesc
        data:
          emotion: emotion
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprintEmotionResponse'
      type: object
      xml:
        name: RespVoiceprintEmotionResponse
    RespVoiceprintGenderResponse:
      example:
        errorDesc: errorDesc
        data:
          isMan: true
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprintGenderResponse'
      type: object
      xml:
        name: RespVoiceprintGenderResponse
    RespVoiceprintMosResponse:
      example:
        errorDesc: errorDesc
        data:
          score: 2.5
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprintMosResponse'
      type: object
      xml:
        name: RespVoiceprintMosResponse
    RespVoiceprintNormalizeResponse:
      example:
        errorDesc: errorDesc
        data:
          score:
          - 100
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprintNormalizeResponse'
      type: object
      xml:
        name: RespVoiceprintNormalizeResponse
    RespVoiceprintQueryResponse:
      example:
        errorDesc: errorDesc
        data:
          isRegister: true
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprintQueryResponse'
      type: object
      xml:
        name: RespVoiceprintQueryResponse
    RespVoiceprintRegisterResponse:
      example:
        errorDesc: errorDesc
        data: ""
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          xml:
            name: VoiceprintRegisterResponse
      type: object
      xml:
        name: RespVoiceprintRegisterResponse
    RespVoiceprintSplitResponse:
      example:
        errorDesc: errorDesc
        data:
        - - startMS: 0
            endMS: 3000
          - startMS: 5000
            endMS: 8000
        - - startMS: 3001
            endMS: 5000
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          example:
          - - startMS: 0
              endMS: 3000
            - startMS: 5000
              endMS: 8000
          - - startMS: 3001
              endMS: 5000
          items:
            example:
            - startMS: 0
              endMS: 3000
            - startMS: 5000
              endMS: 8000
            items:
              $ref: '#/components/schemas/VoiceprintSplitResponse'
            type: array
          type: array
      type: object
      xml:
        name: RespVoiceprintSplitResponse
    RespVoiceprintTTSResponse:
      example:
        errorDesc: errorDesc
        data:
          score: 0
          isTTS: true
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprintTTSResponse'
      type: object
      xml:
        name: RespVoiceprintTTSResponse
    RespVoiceprintThresholdResponse:
      example:
        errorDesc: errorDesc
        data:
          threshold: 0.38
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprintThresholdResponse'
      type: object
      xml:
        name: RespVoiceprintThresholdResponse
    RespVoiceprintVadcheckResponse:
      example:
        errorDesc: errorDesc
        data:
          code: code
          status: status
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprintVadcheckResponse'
      type: object
      xml:
        name: RespVoiceprintVadcheckResponse
    RespVoiceprintVerifyMultiResponse:
      example:
        errorDesc: errorDesc
        data:
          report:
          - unionID: use_one
            score: 99
          - unionID: use_two
            score: 10
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprintVerifyMultiResponse'
      type: object
      xml:
        name: RespVoiceprintVerifyMultiResponse
    RespVoiceprintVerifyResponse:
      example:
        errorDesc: errorDesc
        data:
          score: 0.5
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprintVerifyResponse'
      type: object
      xml:
        name: RespVoiceprintVerifyResponse
    RespVoiceprinttopnVerifyResponse:
      example:
        errorDesc: errorDesc
        data:
          scores:
          - unionID: "123"
            score: 0.5
        hasError: true
        errorId: errorId
      properties:
        hasError:
          type: boolean
        errorId:
          type: string
        errorDesc:
          type: string
        data:
          $ref: '#/components/schemas/VoiceprinttopnVerifyResponse'
      type: object
      xml:
        name: RespVoiceprinttopnVerifyResponse
    UnionIDScore:
      properties:
        unionID:
          description: union ID
          example: "123"
          type: string
        score:
          description: 得分
          example: 0.5
          format: double
          type: number
      type: object
      xml:
        name: UnionIDScore
    UploadResponse:
      example:
        key: "123"
      properties:
        key:
          description: 文件key
          example: "123"
          type: string
      type: object
      xml:
        name: UploadResponse
    Voiceprint1tonVerifyRequest:
      example:
        appName: welab
        samplingRate: samplingRate
        unionIDs:
        - union_id2
        - union_id2
        url: "123456"
        timestamp: 12345
      properties:
        appName:
          description: 应用名字
          example: welab
          type: string
        unionIDs:
          description: union IDs
          example:
          - union_id2
          - union_id2
          items:
            example: union_id2
            type: string
          type: array
        url:
          description: 文件url
          example: "123456"
          type: string
        samplingRate:
          description: sampling rate
          type: string
        timestamp:
          description: 时间戳
          example: 12345
          format: int64
          type: integer
      required:
      - appName
      - samplingRate
      - timestamp
      - unionIDs
      - url
      type: object
      xml:
        name: Voiceprint1tonVerifyRequest
    Voiceprint1tonVerifyResponse:
      example:
        score: 0.5
        unionID: "123"
      properties:
        unionID:
          description: union ID
          example: "123"
          type: string
        score:
          description: 得分
          example: 0.5
          format: double
          type: number
      type: object
      xml:
        name: Voiceprint1tonVerifyResponse
    VoiceprintAgcRequest:
      example:
        mode: 2
        duration: 0
        level: 5
        appName: test
        samplingRate: 8k
        url: x_xxxxx-xxxxx
        timestamp: 123456
      properties:
        appName:
          description: 应用名字
          example: test
          type: string
        url:
          description: 文件url
          example: x_xxxxx-xxxxx
          type: string
        mode:
          description: 0 不做处理,1  模拟音量调节,2 自适应增益,3 固定增益
          example: 2
          format: int32
          type: integer
        level:
          description: db值
          example: 5
          format: int32
          type: integer
        samplingRate:
          description: 采样率,8k/16k
          example: 8k
          type: string
        duration:
          description: 时长(以秒为单位)
          example: 0
          format: double
          type: number
        timestamp:
          description: 时间戳（以秒为单位）
          example: 123456
          format: int64
          type: integer
      required:
      - appName
      - duration
      - samplingRate
      - timestamp
      - url
      type: object
      xml:
        name: VoiceprintAgcRequest
    VoiceprintAgcResponse:
      example:
        key: xx_xxxxx-xxxxx
      properties:
        key:
          description: 增益后文件key
          example: xx_xxxxx-xxxxx
          type: string
      type: object
      xml:
        name: VoiceprintAgcResponse
    VoiceprintClipsRequest:
      example:
        duration: 16000
        appName: test_app
        samplingRate: 16k
        url: xxx-xxx-xxx
        timestamp: 0
      properties:
        appName:
          description: 应用名字
          example: test_app
          type: string
        url:
          description: 文件url
          example: xxx-xxx-xxx
          type: string
        samplingRate:
          description: 采样率,8k/16k
          example: 16k
          type: string
        duration:
          description: 时长(以秒为单位)
          example: 16000
          format: double
          type: number
        timestamp:
          description: 时间戳（以秒为单位）
          example: 0
          format: int64
          type: integer
      required:
      - appName
      - duration
      - samplingRate
      - timestamp
      - url
      type: object
      xml:
        name: VoiceprintClipsRequest
    VoiceprintClipsResponse:
      example:
        ringingSlice:
        - startMS: 0
          endMS: 0
        - startMS: 0
          endMS: 0
        humanSlice:
        - startMS: 0
          endMS: 3000
        - startMS: 5000
          endMS: 8000
        musicSlice:
        - startMS: 0
          endMS: 0
        - startMS: 0
          endMS: 0
        silentSlice:
        - startMS: 0
          endMS: 0
        - startMS: 0
          endMS: 0
        broadcastSlice:
        - startMS: 0
          endMS: 0
        - startMS: 0
          endMS: 0
        busySignalSlice:
        - startMS: 0
          endMS: 0
        - startMS: 0
          endMS: 0
      properties:
        humanSlice:
          description: 人声
          example:
          - startMS: 0
            endMS: 3000
          - startMS: 5000
            endMS: 8000
          items:
            $ref: '#/components/schemas/VoiceprintClipsSlice'
          type: array
        broadcastSlice:
          description: 播报
          items:
            $ref: '#/components/schemas/VoiceprintClipsSlice'
          type: array
        musicSlice:
          description: 音乐
          items:
            $ref: '#/components/schemas/VoiceprintClipsSlice'
          type: array
        busySignalSlice:
          description: 忙音
          items:
            $ref: '#/components/schemas/VoiceprintClipsSlice'
          type: array
        ringingSlice:
          description: 铃声
          items:
            $ref: '#/components/schemas/VoiceprintClipsSlice'
          type: array
        silentSlice:
          description: 静音
          items:
            $ref: '#/components/schemas/VoiceprintClipsSlice'
          type: array
      type: object
      xml:
        name: VoiceprintClipsResponse
    VoiceprintClipsSlice:
      example:
        startMS: 0
        endMS: 0
      properties:
        startMS:
          description: 开始时间
          example: 0
          format: int32
          type: integer
        endMS:
          description: 结束时间
          example: 0
          format: int32
          type: integer
      type: object
      xml:
        name: VoiceprintClipsSlice
    VoiceprintCtcdasrRequest:
      example:
        duration: 0
        appName: appName
        samplingRate: samplingRate
        url: storage/xxxx-xxxx
        timestamp: 0
      properties:
        appName:
          description: 应用名字
          type: string
        url:
          description: 文件url
          example: storage/xxxx-xxxx
          type: string
        samplingRate:
          description: 采样率,8k/16k
          type: string
        duration:
          description: 时长(以秒为单位)
          example: 0
          format: double
          type: number
        timestamp:
          description: 时间戳（以秒为单位）
          example: 0
          format: int64
          type: integer
      required:
      - appName
      - duration
      - samplingRate
      - timestamp
      - url
      type: object
      xml:
        name: VoiceprintCtcdasrRequest
    VoiceprintCtcdasrResponse:
      example:
        asrString: "123456"
      properties:
        asrString:
          description: 数字asr
          example: "123456"
          type: string
      type: object
      xml:
        name: VoiceprintCtcdasrResponse
    VoiceprintDeleteRequest:
      example:
        unionID: unionID
        appName: appName
        timestamp: 123456
      properties:
        appName:
          description: 应用名字
          type: string
        unionID:
          description: union ID
          type: string
        timestamp:
          description: 时间戳（以秒为单位）
          example: 123456
          format: int64
          type: integer
      required:
      - appName
      - timestamp
      - unionID
      type: object
      xml:
        name: VoiceprintDeleteRequest
    VoiceprintDeleteResponse:
      xml:
        name: VoiceprintDeleteResponse
    VoiceprintDenoiseRequest:
      example:
        mode: 0
        duration: 0
        method: rnn
        appName: test
        samplingRate: 8k
        url: url
        timestamp: 123456
      properties:
        appName:
          description: 应用名字
          example: test
          type: string
        url:
          description: 文件url
          type: string
        method:
          description: 降噪方法:rnn/winner
          example: rnn
          type: string
        mode:
          description: 降噪力度:0/1/2/3
          example: 0
          format: int32
          type: integer
        samplingRate:
          description: 采样率,8k/16k
          example: 8k
          type: string
        duration:
          description: 时长(以秒为单位)
          example: 0
          format: double
          type: number
        timestamp:
          description: 时间戳（以秒为单位）
          example: 123456
          format: int64
          type: integer
      required:
      - appName
      - duration
      - method
      - samplingRate
      - timestamp
      - url
      type: object
      xml:
        name: VoiceprintDenoiseRequest
    VoiceprintDenoiseResponse:
      example:
        string: "22"
      properties:
        string:
          description: 降噪后文件key
          example: "22"
          type: string
      type: object
      xml:
        name: VoiceprintDenoiseResponse
    VoiceprintDynamicThresholdRequest:
      example:
        unionID: unionID
        appName: appName
        timestamp: 123456
      properties:
        appName:
          description: 应用名字
          type: string
        unionID:
          description: union ID
          type: string
        timestamp:
          description: 时间戳（以秒为单位）
          example: 123456
          format: int64
          type: integer
      required:
      - appName
      - timestamp
      - unionID
      type: object
      xml:
        name: VoiceprintDynamicThresholdRequest
    VoiceprintDynamicThresholdResponse:
      example:
        threshold: 0.38
      properties:
        threshold:
          description: 阈值
          example: 0.38
          format: double
          type: number
      type: object
      xml:
        name: VoiceprintDynamicThresholdResponse
    VoiceprintEmotionRequest:
      example:
        appName: app-test
        samplingRate: 16k
        url: xxx
        timestamp: 123456
      properties:
        appName:
          description: 应用名字
          example: app-test
          type: string
        url:
          description: 文件url
          example: xxx
          type: string
        samplingRate:
          description: 采样率,8k/16k
          example: 16k
          type: string
        timestamp:
          description: 时间戳（以秒为单位）
          example: 123456
          format: int64
          type: integer
      required:
      - appName
      - samplingRate
      - timestamp
      - url
      type: object
      xml:
        name: VoiceprintEmotionRequest
    VoiceprintEmotionResponse:
      example:
        emotion: emotion
      properties:
        emotion:
          type: string
      type: object
      xml:
        name: VoiceprintEmotionResponse
    VoiceprintGenderRequest:
      example:
        appName: app-test
        samplingRate: 16k
        url: xxx
        timestamp: 123456
      properties:
        appName:
          description: 应用名字
          example: app-test
          type: string
        url:
          description: 文件url
          example: xxx
          type: string
        samplingRate:
          description: 采样率,8k/16k
          example: 16k
          type: string
        timestamp:
          description: 时间戳（以秒为单位）
          example: 123456
          format: int64
          type: integer
      required:
      - appName
      - samplingRate
      - timestamp
      - url
      type: object
      xml:
        name: VoiceprintGenderRequest
    VoiceprintGenderResponse:
      example:
        isMan: true
      properties:
        isMan:
          type: boolean
      type: object
      xml:
        name: VoiceprintGenderResponse
    VoiceprintMosRequest:
      example:
        duration: 0
        appName: appName
        samplingRate: samplingRate
        url: storage/xxxx-xxxx
        timestamp: 0
      properties:
        appName:
          description: 应用名字
          type: string
        url:
          description: 文件url
          example: storage/xxxx-xxxx
          type: string
        samplingRate:
          description: 采样率,8k/16k
          type: string
        duration:
          description: 时长(以秒为单位)
          example: 0
          format: double
          type: number
        timestamp:
          description: 时间戳（以秒为单位）
          example: 0
          format: int64
          type: integer
      required:
      - appName
      - duration
      - samplingRate
      - timestamp
      - url
      type: object
      xml:
        name: VoiceprintMosRequest
    VoiceprintMosResponse:
      example:
        score: 2.5
      properties:
        score:
          description: 分数
          example: 2.5
          format: double
          type: number
      type: object
      xml:
        name: VoiceprintMosResponse
    VoiceprintNormalizeRequest:
      example:
        score:
        - 130.1
        appName: appName
      properties:
        appName:
          description: 应用名字
          type: string
        score:
          description: 分数
          example:
          - 130.1
          items:
            example: 130.1
            format: double
            type: number
          type: array
      required:
      - appName
      - score
      type: object
      xml:
        name: VoiceprintNormalizeRequest
    VoiceprintNormalizeResponse:
      example:
        score:
        - 100
      properties:
        score:
          description: 归一化之后的分数
          example:
          - 100
          items:
            example: 100
            format: double
            type: number
          type: array
      required:
      - score
      type: object
      xml:
        name: VoiceprintNormalizeResponse
    VoiceprintQueryRequest:
      example:
        unionID: unionID
        appName: appName
        timestamp: 123456
      properties:
        appName:
          description: 应用名字
          type: string
        unionID:
          description: union ID
          type: string
        timestamp:
          description: 时间戳（以秒为单位）
          example: 123456
          format: int64
          type: integer
      required:
      - appName
      - timestamp
      - unionID
      type: object
      xml:
        name: VoiceprintQueryRequest
    VoiceprintQueryResponse:
      example:
        isRegister: true
      properties:
        isRegister:
          description: 是否注册
          type: boolean
      type: object
      xml:
        name: VoiceprintQueryResponse
    VoiceprintRegisterRequest:
      example:
        urls:
        - "123"
        - "45"
        - "666"
        unionID: unionID
        appName: appName
        replace: true
        samplingRate: 8k
        timestamp: 123456
      properties:
        appName:
          description: 应用名字
          type: string
        replace:
          description: 是否替换
          type: boolean
        unionID:
          description: union ID
          type: string
        urls:
          description: 文件url数组
          example:
          - "123"
          - "45"
          - "666"
          items:
            example: "123"
            type: string
          type: array
        samplingRate:
          description: sampling rate
          example: 8k
          type: string
        timestamp:
          description: 时间戳
          example: 123456
          format: int64
          type: integer
      required:
      - appName
      - samplingRate
      - timestamp
      - unionID
      type: object
      xml:
        name: VoiceprintRegisterRequest
    VoiceprintRegisterResponse:
      xml:
        name: VoiceprintRegisterResponse
    VoiceprintSplitRequest:
      example:
        duration: 16000
        appName: test_app
        samplingRate: 16k
        url: xxx-xxx-xxx
        timestamp: 0
      properties:
        appName:
          description: 应用名字
          example: test_app
          type: string
        url:
          description: 文件url
          example: xxx-xxx-xxx
          type: string
        samplingRate:
          description: 采样率,8k/16k
          example: 16k
          type: string
        duration:
          description: 时长(以秒为单位)
          example: 16000
          format: double
          type: number
        timestamp:
          description: 时间戳（以秒为单位）
          example: 0
          format: int64
          type: integer
      required:
      - appName
      - duration
      - samplingRate
      - timestamp
      - url
      type: object
      xml:
        name: VoiceprintSplitRequest
    VoiceprintSplitResponse:
      properties:
        startMS:
          description: 开始时间
          example: 0
          format: int32
          type: integer
        endMS:
          description: 结束时间
          example: 3000
          format: int32
          type: integer
      type: object
      xml:
        name: VoiceprintSplitResponse
    VoiceprintTTSRequest:
      properties:
        appName:
          description: 应用名字
          example: app-test
          type: string
        url:
          description: 文件url
          example: xxx
          type: string
        samplingRate:
          description: 采样率,8k/16k
          example: 16k
          type: string
        timestamp:
          description: 时间戳（以秒为单位）
          example: 123456
          format: int64
          type: integer
      required:
      - appName
      - samplingRate
      - timestamp
      - url
      type: object
      xml:
        name: VoiceprintTTSRequest
    VoiceprintTTSResponse:
      example:
        score: 0
        isTTS: true
      properties:
        isTTS:
          type: boolean
        score:
          example: 0
          format: double
          type: number
      type: object
      xml:
        name: VoiceprintTTSResponse
    VoiceprintThresholdRequest:
      example:
        appName: appName
        timestamp: 123456
      properties:
        appName:
          description: 应用名字
          type: string
        timestamp:
          description: 时间戳（以秒为单位）
          example: 123456
          format: int64
          type: integer
      required:
      - appName
      - timestamp
      type: object
      xml:
        name: VoiceprintThresholdRequest
    VoiceprintThresholdResponse:
      example:
        threshold: 0.38
      properties:
        threshold:
          description: 阈值
          example: 0.38
          format: double
          type: number
      type: object
      xml:
        name: VoiceprintThresholdResponse
    VoiceprintVadcheckRequest:
      example:
        duration: 0
        appName: appName
        samplingRate: samplingRate
        url: url
        timestamp: 123456
      properties:
        appName:
          description: 应用名字
          type: string
        url:
          description: 文件url
          type: string
        samplingRate:
          description: sampling rate
          type: string
        duration:
          description: 时长(以秒为单位)
          example: 0
          format: double
          type: number
        timestamp:
          description: 时间戳（以秒为单位）
          example: 123456
          format: int64
          type: integer
      required:
      - appName
      - duration
      - samplingRate
      - timestamp
      - url
      type: object
      xml:
        name: VoiceprintVadcheckRequest
    VoiceprintVadcheckResponse:
      example:
        code: code
        status: status
      properties:
        code:
          description: vad check code
          type: string
        status:
          description: vad check status
          type: string
      type: object
      xml:
        name: VoiceprintVadcheckResponse
    VoiceprintVerifyMultiReport:
      properties:
        unionID:
          description: 唯一id
          example: use_one
          type: string
        score:
          description: 分数
          example: 99
          format: double
          type: number
      type: object
      xml:
        name: VoiceprintVerifyMultiReport
    VoiceprintVerifyMultiRequest:
      example:
        urls:
        - "123456"
        - "1234567"
        appName: welab
        samplingRate: samplingRate
        unionIDs:
        - use_one
        - use_two
        timestamp: 12345
      properties:
        appName:
          description: 应用名字
          example: welab
          type: string
        unionIDs:
          description: 唯一ID
          example:
          - use_one
          - use_two
          items:
            example: use_one
            type: string
          type: array
        urls:
          description: 文件url
          example:
          - "123456"
          - "1234567"
          items:
            example: "123456"
            type: string
          type: array
        samplingRate:
          description: sampling rate
          type: string
        timestamp:
          description: 时间戳
          example: 12345
          format: int64
          type: integer
      required:
      - appName
      - samplingRate
      - timestamp
      - unionIDs
      - urls
      type: object
      xml:
        name: VoiceprintVerifyMultiRequest
    VoiceprintVerifyMultiResponse:
      example:
        report:
        - unionID: use_one
          score: 99
        - unionID: use_two
          score: 10
      properties:
        report:
          description: 结果
          example:
          - unionID: use_one
            score: 99
          - unionID: use_two
            score: 10
          items:
            $ref: '#/components/schemas/VoiceprintVerifyMultiReport'
          type: array
      type: object
      xml:
        name: VoiceprintVerifyMultiResponse
    VoiceprintVerifyRequest:
      example:
        unionID: use_one
        appName: welab
        samplingRate: samplingRate
        url: "123456"
        timestamp: 12345
      properties:
        appName:
          description: 应用名字
          example: welab
          type: string
        unionID:
          description: 唯一ID
          example: use_one
          type: string
        url:
          description: 文件url
          example: "123456"
          type: string
        samplingRate:
          description: sampling rate
          type: string
        timestamp:
          description: 时间戳
          example: 12345
          format: int64
          type: integer
      required:
      - appName
      - samplingRate
      - timestamp
      - unionID
      - url
      type: object
      xml:
        name: VoiceprintVerifyRequest
    VoiceprintVerifyResponse:
      example:
        score: 0.5
      properties:
        score:
          description: 声纹得分
          example: 0.5
          format: double
          type: number
      type: object
      xml:
        name: VoiceprintVerifyResponse
    VoiceprinttopnVerifyRequest:
      example:
        appName: test
        samplingRate: samplingRate
        url: url
        topn: 10
        timestamp: 12345
      properties:
        appName:
          description: 应用名字
          example: test
          type: string
        url:
          description: 文件url
          type: string
        samplingRate:
          description: sampling rate
          type: string
        topn:
          description: top n
          example: 10
          format: int64
          type: integer
        timestamp:
          description: 时间戳
          example: 12345
          format: int64
          type: integer
      required:
      - appName
      - samplingRate
      - timestamp
      - topn
      - url
      type: object
      xml:
        name: VoiceprinttopnVerifyRequest
    VoiceprinttopnVerifyResponse:
      example:
        scores:
        - unionID: "123"
          score: 0.5
      properties:
        scores:
          description: topn排序
          example:
          - unionID: "123"
            score: 0.5
          items:
            $ref: '#/components/schemas/UnionIDScore'
          type: array
      type: object
      xml:
        name: VoiceprinttopnVerifyResponse
    body:
      properties:
        file:
          format: binary
          type: string
